final_project/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', views.register_view, name="register"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

final_project/final_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import include, path


urlpatterns = [
    path('gains_and_losses/', include('gains_and_losses.urls')),
    url(r'^accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    ]

final_project/gains_and_losses/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'gains_and_losses'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('gains/', views.gains, name='gains'),
    #path('all_gains/', views.all_gains, name='all_gains'),
    path('gains_payment/', views.gains_payment, name='gains_payment'),
    path('gains_item/', views.gains_item, name='gains_item'),
    path('gains_other/', views.gains_other, name='gains_other'),
    path('losses/', views.losses, name='losses'),
    ]
    

final_project/accounts/models.py
from django.db import models

# Create your models here.

final_project/gains_and_losses/models.py
from django.db import models
from django.shortcuts import render

# Create your models here.

class Gains_payment(models.Model):
    from_who = models.CharField(max_length=100)
    for_what = models.CharField(max_length=300)
    amount = models.FloatField()
    description = models.CharField(max_length=500, blank = True)
    recived_date = models.DateField('received date')
    add_date = models.DateTimeField(auto_now_add = True)
        
    
class Gains_item(models.Model):
    from_who = models.CharField(max_length=100)
    for_what = models.CharField(max_length=300)
    what = models.CharField(max_length=300)
    description = models.CharField(max_length=500, blank = True)
    recived_date = models.DateField('received date')
    add_date = models.DateTimeField(auto_now_add = True)

    
class Gains_other(models.Model):
    from_who = models.CharField(max_length=100)
    for_what = models.CharField(max_length=300)
    what = models.CharField(max_length=300)
    description = models.CharField(max_length=500, blank = True)
    recived_date = models.DateField('received date')
    add_date = models.DateTimeField(auto_now_add = True)


class Categories_expenses(models.Model):
    category_name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank=True)
    
    def __str__(self):
        return self.category_name


class Bills(models.Model):
    categories_expenses = models.ForeignKey(Categories_expenses, on_delete=models.CASCADE, verbose_name="the related categories_expenses and bills")
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank = True)
    
    def __str__(self):
        return self.name
    
class Basic_expenses(models.Model):
    categories_expenses = models.ForeignKey(Categories_expenses, on_delete=models.CASCADE, verbose_name="the related categories_expenses and basic_expenses")
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank = True)
    
    def __str__(self):
        return self.name
    
    
class Other_expenses(models.Model):
    categories_expenses = models.ForeignKey(Categories_expenses, on_delete=models.CASCADE, verbose_name="the related categories_expenses and other_expenses")
    name = models.CharField(max_length=300)
    description = models.CharField(max_length=500, blank = True)
    
    def __str__(self):
        return self.name
    
    
class Losses(models.Model):
    categories_expenses = models.ForeignKey(Categories_expenses, on_delete=models.CASCADE, verbose_name="the related categories_expenses and losses")
    subcategories_expenses_bills = models.ForeignKey(Bills, on_delete=models.CASCADE, verbose_name="the related subcategory bills and losses", null = True, blank =True)
    subcategories_expenses_basic_expenses = models.ForeignKey(Basic_expenses, on_delete=models.CASCADE, verbose_name="the related subcategory basic_expenses and losses", null = True, blank = True)
    subcategories_expenses_other_expenses = models.ForeignKey(Other_expenses, on_delete=models.CASCADE, verbose_name="the related subcategory other_expenses and losses",  null = True, blank = True)
    how_much = models.FloatField()
    for_what = models.CharField(max_length=500)
    expense_date = models.DateField('expense date')
    add_date = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.for_what
    
   # def choose_subcategory(self):
   #     if self.categories_expanses.name == "bills":
   #         return render(self.subcategories_expenses_bills)
   #     elif self.categories_expanses.name == "basic_expenses":
   #         return render(self.subcategories_expenses_basic_expenses)
   #     else:
   #         return render(self.subcategories_expenses_other_expenses)
    
    
    

final_project/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
    
#def login(request):
    #    return render(request, 'accounts')
    
def register_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect ("gains_and_losses:index")
    else:
        form = UserCreationForm()
    return render(request, "accounts/register.html", {'form':form})
    
    
def login_view(request):
    if request.method =='POST':
        form =AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect ("gains_and_losses:index")
    else:
        form =AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})
    
def logout_view(request):
    if request.method =='POST':
        logout(request)
        return redirect("gains_and_losses:index")

final_project/gains_and_losses/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import Gains_payment, Gains_item, Gains_other, Categories_expenses, Losses, Bills, Basic_expenses, Other_expenses


# Create your views here.


def index(request):
    return render(request, "gains_and_losses/index.html") 
    #HttpResponse("Witaj na stronie głównej aplikacji zysków i strat!")

@login_required()
def gains(request):
    return render(request, "gains_and_losses/gains.html") 

def test(request):
    return render(request, "gains_and_losses/login/test.html") 
#def all_gains(request):
#    gains_payment_list = Gains_payment.objects.all()
#    gains_item_list = Gains_item.objects.all()
#    gains_other_list = Gains_other.objects.all()
#    all_gains_list = [gains_payment_list,gains_item_list,gains_other_list]
#    context = {"al_gains_list": all_gains_list}
#    return render(request, "gains_and_losses/all_gains.html", context)
     
@login_required()
def gains_payment(request):
    gains_payment_list = Gains_payment.objects.all()
    context = {"gains_payment_list": gains_payment_list}
    return render(request, "gains_and_losses/gains_payment.html", context)

@login_required()
def gains_item(request):
    gains_item_list = Gains_item.objects.all()
    context = {"gains_item_list": gains_item_list}
    return render(request, "gains_and_losses/gains_item.html", context)
    
@login_required()
def gains_other(request):
    gains_other_list = Gains_other.objects.all()
    context = {"gains_other_list": gains_other_list}
    return render(request, "gains_and_losses/gains_other.html", context)

@login_required()    
def losses(request):
    losses_list = Losses.objects.all()
    context = {"losses_list": losses_list}
    return render(request, "gains_and_losses/losses.html", context)
    

final_project/accounts/templates/accounts/login.html
    <h1>Login</h1>
    <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>

final_project/accounts/templates/accounts/register.html
<h1>Register</h1>
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
<form class="site-form" action="/accounts/register/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">
</form>

final_project/gains_and_losses/templates/gains_and_losses/all_gains.html
<h1>Zyski</h1>
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
{% if all_gains_list %}
<style>
table, th, td {
    border: 1px solid black;
}
td {
    text-align: center;
}
</style>
<table style="width:100%">
        <tr>
            <th>gains category</th>
            <th>from who</th>
            <th>for what</th>
            <th>amount/what</th>
            <th>recived date</th>
            <th>add date</th>
        </tr>
        {% for gain in all_gains_list %}
                <tr>
                    <td>{{ "gains payment" }}</td>
                    <td>{{ gain.from_who }}</td>
                    <td>{{ gain.for_what }}</td>
                    <td>{{ gain.amount }}</td>
                    <td>{{ gain.description }}</td>
                    <td>{{ gain.recived_date }}</td>
                    <td>{{ gain.add_date }}</td>
                </tr>
          
           
        {% endfor %}
    </ul>
{% else %}
    <p>No gains_list are available.</p>
{% endif %}

final_project/gains_and_losses/templates/gains_and_losses/gains.html
<h1>Wybór przychodów</h1>
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
<h4>Wybór ketegorii</h4>
<ul>
    <!-- <li><p><a href="/gains_and_losses/all_gains/">All gains</a></p></li>-->
    <li><p><a href="/gains_and_losses/gains_payment/">Gains payment</a></p></li>
    <li><p><a href="/gains_and_losses/gains_item/">Gains item</a></p></li>
    <li><p><a href="/gains_and_losses/gains_other/">Gains other</a></p></li>
</ul>

final_project/gains_and_losses/templates/gains_and_losses/gains_item.html
<h1>Przychody - przedmioty</h1>
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
{% if gains_item_list %}
<style>
table, th, td {
    border: 1px solid black;
}
td {
    text-align: center;
}
</style>
    <table style="width:100%">
        <tr>
            <th>from_who</th>
            <th>for what</th>
            <th>what</th>
            <th>description</th>
            <th>recived date</th>
            <th>add date</th>
        </tr>
        {% for gain in gains_item_list %}
            <tr>
                <td>{{ gain.from_who }}</td>
                <td>{{ gain.for_what }}</td>
                <td>{{ gain.what }}</td>
                <td>{{ gain.description }}</td>
                <td>{{ gain.recived_date }}</td>
                <td>{{ gain.add_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No gains_item are available.</p>
{% endif %}

final_project/gains_and_losses/templates/gains_and_losses/gains_other.html
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
<h1>Przychody - pozostałe</h1>
{% if gains_other_list %}
<style>
table, th, td {
    border: 1px solid black;
}
td {
    text-align: center;
}
</style>
    <table style="width:100%">
        <tr>
            <th>from_who</th>
            <th>for what</th>
            <th>what</th>
            <th>description</th>
            <th>recived date</th>
            <th>add date</th>
        </tr>
        {% for gain in gains_other_list %}
            <tr>
                <td>{{ gain.from_who }}</td>
                <td>{{ gain.for_what }}</td>
                <td>{{ gain.what }}</td>
                <td>{{ gain.description }}</td>
                <td>{{ gain.recived_date }}</td>
                <td>{{ gain.add_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No gains_other are available.</p>
{% endif %}

final_project/gains_and_losses/templates/gains_and_losses/gains_payment.html
<h1>Przychody - wypłata</h1>
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
{% if gains_payment_list %}
<style>
table, th, td {
    border: 1px solid black;
}
td {
    text-align: center;
}
</style>
    <table style="width:100%">
        <tr>
            <th>from_who</th>
            <th>for what</th>
            <th>amount</th>
            <th>description</th>
            <th>recived date</th>
            <th>add date</th>
        </tr>
        {% for gain in gains_payment_list %}
            <tr>
                <td>{{ gain.from_who }}</td>
                <td>{{ gain.for_what }}</td>
                <td>{{ gain.amount }}</td>
                <td>{{ gain.description }}</td>
                <td>{{ gain.recived_date }}</td>
                <td>{{ gain.add_date }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No gains_payment are available.</p>
{% endif %}

final_project/gains_and_losses/templates/gains_and_losses/index.html
<h1>Wiataj na stronie głównej aplikacji do rejetrowania zysków i strat</h1>

<h4>Aby korzystać w pełni z aplikacji nalezy najpierw się zarejestrować klikając w przycisk "Register", po rejestracji będziesz miał/a możliwość przeglądania swoich zysków (gains) oraz strat(losses) poprzez klikniecię odpowiadających im nazw. Zyski zostały podzielone na 3 kategorie zyski z wypłaty, zyski jako przedmioty oraz inne. Wydatki zostały skumulowane do jedej tabeli ale podczas dodawania każdego wydatku istnieje szereg podkategori (można tworzyć nowe) w 3 głównych kategoriach (rachunki, podstawowe wydatki oraz inne wydatki) dzięki czemu można odpowiednio dany wydatek umiejscowić. 
</h4>
<nav>
            <ul>
                
                    <form class="register-link" action="{% url 'accounts:register' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Register</button>
                    </form>
                
            </ul>
            <ul>
                
                    <form class="login-link" action="{% url 'accounts:login' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Login</button>
                    </form>
                
            </ul>
            <ul>
                
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                
            </ul>
        </nav>
<h4>Wybór ketegorii</h4>
<ul>
    <li><p><a href="/gains_and_losses/gains/">Gains</a></p></li>
    <li><p><a href="/gains_and_losses/losses/">Losses</a></p></li>
</ul>

final_project/gains_and_losses/templates/gains_and_losses/losses.html
<h1>Straty</h1>
<nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
{% if losses_list %}
<style>
table, th, td {
    border: 1px solid black;
}
td {
    text-align: center;
}
</style>
    <table style="width:100%">
        <tr>
            <th>category name</th>
            <th>subcategory name</th>
            <th>how much</th>
            <th>for what</th>
            <th>expense date</th>
            <th>add date</th>
        </tr>
        {% for loss in losses_list %}
            {% if loss.subcategories_expenses_bills.name != NULL%}
                <tr>
                    <td>{{ loss.categories_expenses.category_name }}</td>
                    <td>{{ loss.subcategories_expenses_bills.name }}</td>
                    <td>{{ loss.how_much }}</td>
                    <td>{{ loss.for_what }}</td>
                    <td>{{ loss.expense_date }}</td>
                    <td>{{ loss.add_date }}</td>
                </tr>
            {% elif  loss.subcategories_expenses_basic_expenses.name != NULL%}
                <tr>
                    <td>{{ loss.categories_expenses.category_name }}</td>
                    <td>{{ loss.subcategories_expenses_basic_expenses.name }}</td>
                    <td>{{ loss.how_much }}</td>
                    <td>{{ loss.for_what }}</td>
                    <td>{{ loss.expense_date }}</td>
                    <td>{{ loss.add_date }}</td>
                </tr>
            {% elif loss.subcategories_expenses_other_expenses.name != NULL%}
                 <tr>
                    <td>{{ loss.categories_expenses.category_name }}</td>
                    <td>{{ loss.subcategories_expenses_other_expenses.name }}</td>
                    <td>{{ loss.how_much }}</td>
                    <td>{{ loss.for_what }}</td>
                    <td>{{ loss.expense_date }}</td>
                    <td>{{ loss.add_date }}</td>
                </tr>
            {% else %}
                <p>This loss dose not belong to any subcategories </p>
            {% endif %}
        {% endfor %}
    </ul>
{% else %}
    <p>No losses_list are available.</p>
{% endif %}

final_project/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nazwa karty w przeglądarce</title>
</head>
<body>
     
    <h1>cos</h1>
    <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {%csrf_token%}
                    <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    
    
    {% block content %}
    {% endblock %}
    
    <footer>SDA 2020</footer>
</body>
</html>